name: get-completed-tasks

on:
  workflow_call:
    inputs:
      since:
        type: string
        description: 'Since when to get completed tasks'
        required: true
        default: 1900-01-01T00:00
      until:
        type: string
        description: 'Until when to get completed tasks'
        required: false
        default: 1900-01-01T10:13
      url:
        type: string
        description: 'URL of the Todoist API'
        required: false
        default: https://api.todoist.com/sync/v9/completed/get_all
    secrets:
      token:
        required: true

jobs:
  get-completed-tasks:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: Get Completed Tasks
        run: |                
          # if dates not passed, default to 14 days ago and today
          if ($since -eq '1900-01-01T00:00') {
            $since = (get-date).AddDays(-14).ToString('yyyy-MM-dd')
          }
          if ($until -eq '1900-01-01T00:00') {
            $until = (get-date).ToString('yyyy-MM-dd')
          }

          # get tasks, save as json
          $output = (curl ${{ inputs.url }} -d since="${since}" -d until="${until}" -d limit=200 -H "Authorization: Bearer ${{ secrets.token }}")

          # output string
          echo "tasks=$output" >> "$GITHUB_OUTPUT"

          # output clean object to csv
          ($output | ConvertFrom-Json).Items | Select-Object completed_on, content | Export-Csv -Path tasks.csv

        shell: pwsh

      - name: upload tasks.csv
        uses: actions/upload-artifact@v2
        with:
          name: tasks.csv
          path: tasks.csv

      - name: upload response.txt
        uses: actions/upload-artifact@v2
        with:
          name: response.txt
          path: response.txt
        if: success() || failure()